title: "Naeem's Academic Website"
description: "A personal academic website built with Jekyll and Minimal Mistakes"
url: "https://naeemshb.github.io"
baseurl: ""  # Leave empty if your site is at username.github.io

# Minimal Mistakes theme (remote)
remote_theme: "mmistakes/minimal-mistakes"

# Plugins to enhance the site
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-sass-converter

# Load custom SCSS from these folders
sass:
  load_paths:
    - _sass
    - node_modules

# Use one of Minimal Mistakes’ built-in skins: "dark", "default", "solarized", etc.
minimal_mistakes_skin: "dark"

# Default layouts for pages/posts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

# Navigation bar links
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Research"
    url: "/research/"
  - title: "Publications"
    url: "/publications/"
  # Add or remove items as you wish:
  # - title: "CV"
  #   url: "/cv/"
  # - title: "Contact"
  #   url: "/contact/"

# Author information (for big circular avatar + details at top)
author:
  name: "Naeem Shahabi Sani"
  avatar: "/assets/images/profile.jpg"  # Ensure 'profile.jpg' exists under 'assets/images/'
  location: "Norman, Oklahoma, USA"
  job_title: "PhD Student at OU"

  social:
    - label: "Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=acImM0IAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/naeem-shahabi-sani-a50909254/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/naeemshb"

# Configure pagination if you create a blog with multiple posts
paginate: 5
paginate_path: "page:num"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
