remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

# Optional: Keep or remove your old 'theme:' line if you have it
# theme: jekyll-theme-minimal  <-- remove or comment out if present

# You can also keep other settings like title, description, etc.
title: "My Personal Site"
description: "A site built with Minimal Mistakes"
