# -----------------------------------------------------------
# Basic Site Settings
# -----------------------------------------------------------
title: "My Academic Website"
description: "A personal academic website built with Minimal Mistakes"
url: "https://naeemshb.github.io"
baseurl: ""  # If hosting at 'username.github.io', leave this empty

# -----------------------------------------------------------
# GitHub & Build Configuration
# -----------------------------------------------------------
# Minimal Mistakes remote theme
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# -----------------------------------------------------------
# Minimal Mistakes Theme Settings
# -----------------------------------------------------------
# Remove or comment out any default "theme:" line if present
# theme: jekyll-theme-minimal # not needed because remote_theme is used

# Reading and Layout
markdown: kramdown
show_excerpt_separator: true

# Default Layouts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false

# Pagination
paginate: 5
paginate_path: "page:num"

# Enable or disable specific features
minimal_mistakes_skin: "default"  # For color schemes see the MM docs
# Minimal Mistakes includes many additional config options, such as:
#   - author profiles
#   - social links
#   - analytics
#   - table of contents
# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/

# -----------------------------------------------------------
# Site Navigation
# -----------------------------------------------------------
# Provide a structured menu for quick navigation.
# The "title" will appear in the site’s navigation bar.
# "url" references either an internal page (e.g. /about/) or external link.

nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Research"
    url: "/research/"
  - title: "Publications"
    url: "/publications/"
  - title: "Blog"
    url: "/blog/"
  - title: "CV"
    url: "/cv/"
  - title: "Contact"
    url: "/contact/"

# -----------------------------------------------------------
# SEO and Social
# -----------------------------------------------------------
# Optional but recommended
google_site_verification: "YOUR_GOOGLE_SITE_VERIFICATION_CODE"

# Social profiles (replace with your own)
author:
  name: "Naeem Shahabi Sani"
  # Optional fields:
  # avatar: "/assets/images/profile.jpg"
  social:
    twitter: your_twitter_username
    linkedin: your_linkedin_slug
    scholar: https://scholar.google.com/citations?hl=en&user=acImM0IAAAAJ
    github: your_github_username
    orcid: your_orcid_id

# -----------------------------------------------------------
# Build Settings
# -----------------------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Activate Jekyll SEO Tag and other recommended plugins
# so <head> metadata, sitemap, etc. get generated.
