# -----------------------------------------------------------
# Basic Site Settings
# -----------------------------------------------------------
title: "My Academic Website"
description: "An academic website built with Jekyll & Minimal Mistakes"
url: "https://naeemshb.github.io"
baseurl: ""  # leave empty if using username.github.io
twitter_username: "YourTwitterID"
github_username: "naeemshb"

# -----------------------------------------------------------
# Theme and Plugins
# -----------------------------------------------------------
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Minimal Mistakes options
minimal_mistakes_skin: "dark"  # Switch to a dark color scheme

# -----------------------------------------------------------
# Default Layouts
# -----------------------------------------------------------
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single

# -----------------------------------------------------------
# Navigation
# -----------------------------------------------------------
# These links will appear in the top menu bar.
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Research"
    url: "/research/"
  - title: "Publications"
    url: "/publications/"
  - title: "Contact"
    url: "/contact/"

# -----------------------------------------------------------
# Author and Social
# -----------------------------------------------------------
author:
  name: "Naeem Shahabi Sani"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD student in Computer Science at the University of Oklahoma, focusing on feature engineering, bio-inpired algorithms and classification."
  location: "Norman, Oklahoma, USA"

# Example extended social links
# (uncomment & fill in as desired)
# social:
#   - label: "LinkedIn"
#     icon: "fab fa-linkedin"
#     url: "https://www.linkedin.com/in/YOUR_PROFILE"
#   - label: "Scholar"
#     icon: "ai ai-google-scholar"
#     url: "https://scholar.google.com/citations?user=YOUR_USER_ID"
#   - label: "GitHub"
#     icon: "fab fa-github"
#     url: "https://github.com/naeemshb"

# -----------------------------------------------------------
# Pagination + Build Settings
# -----------------------------------------------------------
paginate: 5
paginate_path: "page:num"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
