title: ""
description: "A personal academic website built with Jekyll and Minimal Mistakes"
url: "https://naeemshb.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-sass-converter

sass:
  load_paths:
    - _sass
    - node_modules

# Make sure Jekyll includes main.scss in the build:
include:
  - main.scss

minimal_mistakes_skin: "dark"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Research"
    url: "/research/"
  - title: "Publications"
    url: "/publications/"

author:
  name: "Naeem Shahabi Sani"
  avatar: "/assets/images/profile.jpg"
  location: "Norman, Oklahoma, USA"
  job_title: "Teaching Assistant"
  social:
    - label: ""
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=acImM0IAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/naeem-shahabi-sani-a50909254/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/naeemshb"

paginate: 5
paginate_path: "page:num"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
